src/Entity/User.php
<?php
declare(strict_types=1);

namespace DR\GitCommitNotification\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use DR\GitCommitNotification\Repository\UserRepository;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $email = null;

    /** @phpstan-var Collection<int, Rule> */
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Rule::class, orphanRemoval: true)]
    private Collection $rules;

    public function __construct()
    {
        $this->rules = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection<int, Rule>
     */
    public function getRules(): Collection
    {
        return $this->rules;
    }

    public function addRule(Rule $rule): self
    {
        if (!$this->rules->contains($rule)) {
            $this->rules[] = $rule;
            $rule->setUser($this);
        }

        return $this;
    }

    public function removeRule(Rule $rule): self
    {
        if ($this->rules->removeElement($rule)) {
            // set the owning side to null (unless already changed)
            if ($rule->getUser() === $this) {
                $rule->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->email;
    }

    /**
     * @return string[]
     * @see UserInterface
     */
    public function getRoles(): array
    {
        return ['ROLE_USER'];
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // no credentials, authentication via SSO only.
    }
}

templates/app/admin/credentials.html.twig
{% extends 'app/app.base.html.twig' %}

{% block page_content %}
    <h1 class="mb-4 mt-2">{{ 'repository.credentials'|trans }}</h1>

    {% include 'app/flash/flashes.html.twig' %}

    {% if credentialsViewModel.credentials %}
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th scope="col">{{ 'id'|trans }}</th>
            <th scope="col">{{ 'name'|trans }}</th>
            <th scope="col">{{ 'authentication.type'|trans }}</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        {%- for credential in credentialsViewModel.credentials -%}
            <tr>
                <td>{{ credential.id }}</td>
                <td>{{ credential.name }}</td>
                <td>{{ credential.authType }}</td>
                <td>
                    <a href="{{ path('DR\\Review\\Controller\\App\\Admin\\Credentials\\CredentialController', {id: credential.id}) }}"
                       class="btn btn-success btn-sm">
                        <i class="bi-pencil-square"></i>
                    </a>

                    <form method="POST" class="d-inline-block"
                          action="{{ path('DR\\Review\\Controller\\App\\Admin\\Credentials\\DeleteCredentialController', {id: credential.id}) }}"
                            {{ stimulus_controller('component--confirm-submit') }}
                          data-confirm-message="{{ 'are.you.sure.you.want.to.delete.this'|trans }}">
                        <input type="hidden" name="_method" value="DELETE" />
                        <button type="submit" class="btn btn-danger btn-sm">
                            <i class="bi-trash"></i>
                        </button>
                    </form>
                </td>
            </tr>
        {%- endfor -%}
        <tbody>
    </table>
    {% endif %}

    <a href="{{ path('DR\\Review\\Controller\\App\\Admin\\Credentials\\CredentialController') }}" class="btn btn-outline-primary">
        <i class="bi-plus"></i>
        {{ 'credential.new'|trans }}
    </a>

    <br><br>
{% endblock %}

templates/app/admin/edit_credential.html.twig
{% extends 'app/app.base.html.twig' %}

{% block page_content %}
    <h1 class="mb-4 mt-2">
        {% if editCredentialModel.credential.id is same as null %}
            {{ 'add.credential'|trans }}
        {% else %}
            {{ 'edit.credential'|trans }} #{{ editCredentialModel.credential.id }}
        {% endif %}
    </h1>

    {% if editCredentialModel.credential.id %}
        <div class="alert alert-info" role="alert">
            {{ 'empty.password.will.be.kept'|trans }}
        </div>
    {% endif %}

    {{ form(editCredentialModel.form ) }}

{% endblock %}

templates/app/admin/edit_repository.html.twig
{% extends 'app/app.base.html.twig' %}

{%- macro checkboxFieldRow(formField) -%}
    <div class="form-group row mb-2">
        <label class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            {{ form_widget(formField) }}
        </div>
    </div>
{%- endmacro -%}

{%- macro inputFieldRow(formField) -%}
    <div class="row mb-3">
        {{ form_label(formField, null, {label_attr: {class: 'col-sm-2 col-form-label'}}) }}
        <div class="col-sm-10">
            {{ form_widget(formField) }}
            {{ form_errors(formField) }}
            {% if formField.vars.help %}
                <small class="text-secondary">{{ formField.vars.help|trans(formField.vars.help_translation_parameters)|raw }}</small>
            {% endif %}
        </div>
    </div>
{%- endmacro -%}
{%- from _self import inputFieldRow -%}
{%- from _self import checkboxFieldRow -%}

{% block page_content %}
    {% set form = editRepositoryModel.form %}

    <h1 class="mb-4 mt-2">
        {% if editRepositoryModel.repository.id is same as null %}
            {{ 'add.repository'|trans }}
        {% else %}
            {{ 'edit.repository'|trans }} #{{ editRepositoryModel.repository.id }}
        {% endif %}
    </h1>

    {{ form_start(form) }}
    {{ form_errors(form) }}

    {{ checkboxFieldRow(form.repository.active) }}
    {{ checkboxFieldRow(form.repository.favorite) }}

    {{ inputFieldRow(form.repository.name) }}
    {{ inputFieldRow(form.repository.displayName) }}
    {{ inputFieldRow(form.repository.mainBranchName) }}

    <h4>Git</h4>
    <hr>
    {{ inputFieldRow(form.repository.url) }}
    {{ inputFieldRow(form.repository.credential) }}
    {{ inputFieldRow(form.repository.gitType) }}

    <h4>{{ 'update.frequency'|trans }}</h4>
    <hr>
    {{ inputFieldRow(form.repository.updateRevisionsInterval) }}
    {{ inputFieldRow(form.repository.validateRevisionsInterval) }}

    {% if form.repository.gitlabProjectId is defined %}
        <h4>{{ 'integrations'|trans }}</h4>
        <hr>
        {{ inputFieldRow(form.repository.gitlabProjectId) }}
    {% endif %}


    <div class="pt-3">
        {{ form_widget(form.save) }}

        <a href="{{ path('DR\\Review\\Controller\\App\\Admin\\RepositoriesController') }}" class="btn btn-outline-primary">
            {{ 'cancel'|trans }}
        </a>
    </div>

    {{ form_rest(form) }}
    {{ form_end(form) }}

{% endblock %}

templates/app/admin/edit_webhook.html.twig
{% extends 'app/app.base.html.twig' %}

{% block page_content %}
    {% set form = editWebhookModel.form %}

    <h1 class="mb-4 mt-2">
        {% if editWebhookModel.webhook.id is same as null %}
            {{ 'add.webhook'|trans }}
        {% else %}
            {{ 'edit.webhook'|trans }} #{{ editWebhookModel.webhook.id }}
        {% endif %}
    </h1>

    {{ form_start(form) }}
    {{ form_errors(form) }}

    {{ form_row(form.webhook.url) }}
    {{ form_row(form.webhook.authorization) }}
    {{ form_row(form.webhook.retries) }}
    {{ form_row(form.webhook.enabled) }}
    {{ form_row(form.webhook.verifySsl) }}

    {{ form_label(form.webhook.repositories) }}
    <div class="repository-columns mb-3">
        {{ form_widget(form.webhook.repositories) }}
    </div>

    {{ form_end(form) }}

{% endblock %}

templates/app/admin/repositories.html.twig
{% extends 'app/app.base.html.twig' %}

{% block page_content %}
    <h1 class="mb-4 mt-2">{{ 'repositories'|trans }}</h1>

    {% include 'app/flash/flashes.html.twig' %}

    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th scope="col">{{ 'repository.id'|trans }}</th>
            <th scope="col"></th>
            <th scope="col">{{ 'name'|trans }}</th>
            <th scope="col">{{ 'display.name'|trans }}</th>
            <th scope="col">{{ 'main.branch'|trans }}</th>
            <th scope="col">{{ 'last.updated'|trans }}</th>
            <th scope="col">{{ 'last.validated'|trans }}</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        {%- for repository in repositoriesViewModel.repositories -%}
            <tr>
                <td>{{ repository.id }}</td>
                <td>
                    {% if repository.active %}
                        <i class="bi bi-check-circle-fill text-success" title="{{ 'active'|trans }}"></i>
                    {% else %}
                        <i class="bi bi-check-circle-fill text-secondary" title="{{ 'active'|trans }}"></i>
                    {% endif %}

                    {% if repository.favorite %}
                        <i class="bi bi-star-fill text-warning" title="{{ 'favorite'|trans }}"></i>
                    {% endif %}
                </td>
                <td>{{ repository.name }}</td>
                <td>{{ repository.displayName }}</td>
                <td>{{ repository.mainBranchName }}</td>
                <td>{{ repository.updateRevisionsTimestamp|format_datetime('short', 'short') }}</td>
                <td>{{ repository.validateRevisionsTimestamp|format_datetime('short', 'short') }}</td>
                <td>
                    <a href="{{ path('DR\\Review\\Controller\\App\\Admin\\RepositoryController', {id: repository.id}) }}"
                       class="btn btn-success btn-sm">
                        <i class="bi-pencil-square"></i>
                    </a>
                    <a href="{{ path('DR\\Review\\Controller\\App\\Admin\\ValidateRevisionsController', {id: repository.id}) }}"
                       class="btn btn-primary btn-sm" title="{{ 'revalidate.revisions'|trans }}">
                        <i class="bi-arrow-clockwise"></i>
                    </a>
                </td>
            </tr>
        {%- endfor -%}
        <tbody>
    </table>

    <a href="{{ path('DR\\Review\\Controller\\App\\Admin\\RepositoryController') }}" class="btn btn-outline-primary mb-3">
        <i class="bi-plus"></i>
        {{ 'repository.new'|trans }}
    </a>

{% endblock %}

templates/app/admin/users.html.twig
{% extends 'app/app.base.html.twig' %}

{% block page_content %}
    {% set profileChoices = constant('DR\\Review\\Security\\Role\\Roles::PROFILE_NAMES') %}

    <h1 class="mb-4 mt-2">{{ 'users'|trans }}</h1>

    {% include 'app/flash/flashes.html.twig' %}

    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th scope="col">{{ 'user.id'|trans }}</th>
            <th scope="col">{{ 'name'|trans }}</th>
            <th scope="col">{{ 'email'|trans }}</th>
            <th scope="col">{{ 'user.role'|trans }}</th>
        </tr>
        </thead>
        <tbody>
        {%- for user in usersViewModel.users -%}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.email }}</td>
                <td>
                    {% set form = usersViewModel.forms[user.id] %}
                    {{ form_start(form) }}
                    {{ form_widget(form.roles) }}
                    {{ form_end(form) }}
                </td>
            </tr>
        {%- endfor -%}
        <tbody>
    </table>
{% endblock %}

templates/app/admin/webhooks.html.twig
{% extends 'app/app.base.html.twig' %}

{% block page_content %}
    <h1 class="mb-4 mt-2">{{ 'webhooks'|trans }}</h1>

    {% include 'app/flash/flashes.html.twig' %}

    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th scope="col">{{ 'id'|trans }}</th>
            <th scope="col">{{ 'enabled'|trans }}</th>
            <th scope="col">{{ 'name'|trans }}</th>
            <th scope="col">{{ 'retries'|trans }}</th>
            <th scope="col">{{ 'verify.ssl'|trans }}</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        {%- for webhook in webhooksViewModel.webhooks -%}
            <tr>
                <td>{{ webhook.id }}</td>
                <td>
                    {% if webhook.enabled %}
                        <i class="bi bi-check-circle-fill text-success" title="{{ 'active'|trans }}"></i>
                    {% else %}
                        <i class="bi bi-check-circle-fill text-secondary" title="{{ 'active'|trans }}"></i>
                    {% endif %}
                </td>
                <td>{{ webhook.url }}</td>
                <td>{{ webhook.retries }}</td>
                <td>
                    {% if webhook.verifySsl %}
                        <i class="bi bi-check-circle-fill text-success" title="{{ 'active'|trans }}"></i>
                    {% else %}
                        <i class="bi bi-check-circle-fill text-secondary" title="{{ 'active'|trans }}"></i>
                    {% endif %}
                </td>
                <td>
                    <a href="{{ path('DR\\Review\\Controller\\App\\Admin\\Webhook\\WebhookController', {id: webhook.id}) }}"
                       class="btn btn-success btn-sm">
                        <i class="bi-pencil-square"></i>
                    </a>

                    <form method="POST" class="d-inline-block"
                          action="{{ path('DR\\Review\\Controller\\App\\Admin\\Webhook\\DeleteWebhookController', {id: webhook.id}) }}"
                            {{ stimulus_controller('component--confirm-submit') }}
                          data-confirm-message="{{ 'are.you.sure.you.want.to.delete.this'|trans }}">
                        <input type="hidden" name="_method" value="DELETE" />
                        <button type="submit" class="btn btn-danger btn-sm">
                            <i class="bi-trash"></i>
                        </button>
                    </form>
                </td>
            </tr>
        {%- endfor -%}
        <tbody>
    </table>

    <a href="{{ path('DR\\Review\\Controller\\App\\Admin\\Webhook\\WebhookController') }}" class="btn btn-outline-primary">
        <i class="bi-plus"></i>
        {{ 'webhook.new'|trans }}
    </a>

    <br><br>
{% endblock %}